### ISSUE TITLE
training is good, eval is worse

### ISSUE THREAD

**Issue by ChiefGodMan** [raymon-tian/hourglass-facekeypoints-detection#2]
When I trained hg model using 300w datasets, and the training result showed is good, but is worse when I use eval mode. Maybe it's because of the bn layer.  Have you met this problem? What should I do for it?

**Comment by raymon-tian** [comment]
No, I didn't meet the problem. Did you set `net.eval()` before evaluation？

**Comment by raymon-tian** [comment]
@ailias No, I didn't meet the problem. Did you set net.eval() before evaluation？

**Comment by thruster1996** [comment]
@ailias ，I meet the same problem just like you. After finishing training, if I set the net to eval, then output of the net seems to be much more worse than the train mode:(

**Comment by TingmanYan** [comment]
I have met the same problem when training the hg model on MPII dataset.
I'm training on a Titan Xp GPU, Pytorch 0.4.1.
Changing hg.py, line 22-23
```
self.res2 = Residual(128, 128)
self.res3 = Residual(128, self._nFeats)
```
to
```
self.res2 = Residual(128, self._nFeats)
self.res3 = Residual(self._nFeats, self._nFeats)
```
solved my problem.
Hope it will help you too.

**Comment by 4Statistics** [comment]
> 
> 
> When I trained hg model using 300w datasets, and the training result showed is good, but is worse when I use eval mode. Maybe it's because of the bn layer. Have you met this problem? What should I do for it?

Can you tell me how to run the code ?
python train.py
-----
Traceback (most recent call last):
  File "train.py", line 123, in <module>
    net = KFSGNet()

TypeError: new() received an invalid combination of arguments - got (float, int, int, int), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
 * (object data, torch.device device)
----------
Thank you very much .
Best wishes.

**Comment by silvercherry** [comment]
请问能将训练集分享出来吗

**Comment by silvercherry** [comment]
> > When I trained hg model using 300w datasets, and the training result showed is good, but is worse when I use eval mode. Maybe it's because of the bn layer. Have you met this problem? What should I do for it?
> 
> ## Can you tell me how to run the code ?
> python train.py
> Traceback (most recent call last):
> File "train.py", line 123, in
> net = KFSGNet()
> 
> TypeError: new() received an invalid combination of arguments - got (float, int, int, int), but expected one of:
> 
> * (torch.device device)
> * (torch.Storage storage)
> * (Tensor other)
> * (tuple of ints size, torch.device device)
> * (object data, torch.device device)
> 
> Thank you very much .
> Best wishes.

have you solve this problem?

**Comment by ilaij0810** [comment]
in models.py, from line 64, should be modified:
            nn.Conv2d(ins,int(outs//2),1),
            nn.BatchNorm2d(int(outs//2)),
            nn.ReLU(inplace=True),
            nn.Conv2d(int(outs//2),int(outs//2),3,1,1),
            nn.BatchNorm2d(int(outs//2)),
            nn.ReLU(inplace=True),
            nn.Conv2d(int(outs//2),outs,1)
